AWSTemplateFormatVersion: '2010-09-09'

Description: 'ec2 instance'

Parameters:
  KeyName:
    Type: String
    Description: KeyPair Name 
  SubnetId:
    Type: String
    Description: Subnet ID
  SecurityGroupId:
    Type: String
    Description: SecurityGroup ID

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-03dceaabddff8067e' # Amazon Linux 2023
      InstanceType: 't2.medium' # t2.micro take a long time to build flutter web app, so it selects more larger type. 
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: 'gp2'
            DeleteOnTermination: true
            VolumeSize: 8
      InstanceInitiatedShutdownBehavior: 'stop'
      KeyName: !Ref KeyName
      Monitoring: false
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      Tenancy: 'default'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          yum update -y
          # create ec2-user group
          ## apache and jenkins belong to ec2-user group
          usermod -aG ec2-user ec2-user
          # apache
          echo userdata: install apache
          yum install -y httpd
          ## give parmission to apache
          usermod -aG ec2-user apache
          chown -R ec2-user:ec2-user /var/www
          chmod -R g+wrxs /var/www
          # run
          systemctl start httpd
          systemctl enable httpd
          # git install for flutter and jenkins.
          yum install -y git
          # flutter
          ## see <https://docs.flutter.dev/get-started/install/linux>
          echo userdata: install flutter
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.10.2-stable.tar.xz
          mkdir /usr/bin/flutter
          tar xf flutter_linux_3.10.2-stable.tar.xz -C /usr/bin/
          rm -f flutter_linux_3.10.2-stable.tar.xz
          # fontconfig
          ## jenkins need freetype. 
          ## fontconfig include freetype.
          ### if you don't install freetype, jenkins throw the bellow error
          #### java.lang.UnsatisfiedLinkError: /usr/lib/jvm/jdk-17-oracle-x64/lib/libfontmanager.so: libfreetype.so.6:cannot open shared object file: No such file or directory
          echo userdata: install fontconfig
          yum install -y fontconfig
          # java
          ## jenkins need java.
          ## if you are Amazon Linux2, use comannd "amazon-linux-extras install -y java-openjdk11"
          echo userdata: install java
          wget -O java.rpm https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm
          rpm -ivh java.rpm
          rm -f java.rpm
          # jenkins
          echo userdata: install jenkins
          ## install
          wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
          rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
          yum install -y jenkins
          ## give parmission
          usermod -aG ec2-user jenkins 
          chown -R ec2-user:ec2-user /usr/bin/flutter
          chmod -R g+wrxs /usr/bin/flutter
          ## run
          systemctl start jenkins
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}'
  EIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref EC2Instance
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}'

Outputs:
  EC2InstanceId:
    Value: !Ref EC2Instance
    Description: EC2InstanceId of Apache Server
